import { expect, test } from "../fixtures/auth.fixture";
import { BoardPage } from "../pages/BoardPage";
import { BoardsPage } from "../pages/BoardsPage";

// Font rendering differs enough between operating systems that pixel-diff
// baselines aren't portable across them - a known, general limitation of
// screenshot-based visual regression. Both a Windows baseline (for local dev)
// and a Linux baseline (generated by CI itself, not a local approximation) are
// committed under tests/visual.spec.ts-snapshots/, distinguished automatically
// by Playwright's platform-suffixed naming (-win32 vs -linux).
test("board view with lists and cards matches its visual baseline", async ({ authenticatedPage }) => {
  const boardsPage = new BoardsPage(authenticatedPage);
  await boardsPage.createBoard("Visual Regression Board");
  await boardsPage.boardLink("Visual Regression Board").click();

  const boardPage = new BoardPage(authenticatedPage);
  await boardPage.addList("To Do");
  await boardPage.addList("Doing");
  await boardPage.addCard("To Do", "Write tests");
  await boardPage.addCard("To Do", "Review PR");

  await expect(authenticatedPage).toHaveScreenshot("board-view.png");
});
